import { z } from 'zod';

/**
 * The map catalog as it crosses the IPC boundary (03-technical-design.md
 * §5.3, reworked to the full ADR-045 profile surface in E22.3):
 * renderer-facing projections of the maps module's data. Contract-owned like
 * `game-state.ts` — `shared` never imports from modules, so these schemas
 * define the IPC shape independently of the module shapes; `app/ipc` maps
 * between the two. GSI resolution inputs (`gsiNames`), file names, and the
 * bundled default layouts never cross — the renderer does not need them.
 */

/** Catalog map id (folder-name convention, data/maps/README.md). */
export const mapIdSchema = z.string().min(1).max(64);

/** Profile id as generated by main (UUID); the cap is the boundary guard. */
export const profileIdSchema = z.string().min(1).max(64);

/**
 * A profile name as the renderer sends it: surrounding whitespace is
 * insignificant (trimmed at the boundary, matching the module's
 * normalization), never empty, length-capped as the boundary guard.
 */
export const profileNameSchema = z.string().trim().min(1).max(120);

/** Callout positions are normalized to the map image: 0–1 on both axes (ADR-045). */
export const calloutSchema = z.object({
  name: z.string().min(1).max(200),
  x: z.number().min(0).max(1),
  y: z.number().min(0).max(1),
});

export type CatalogCallout = z.infer<typeof calloutSchema>;

/** The `maps.updateCallouts` set bound — the editor disables add at the cap. */
export const MAX_CALLOUTS_PER_PROFILE = 1_000;

/**
 * A callout set as `maps.updateCallouts` accepts it: bounded (boundary
 * guard) and with unique names, so a duplicate is the named
 * `INVALID_REQUEST` instead of surfacing as an internal module error.
 */
export const calloutListSchema = z
  .array(calloutSchema)
  .max(MAX_CALLOUTS_PER_PROFILE)
  .superRefine((callouts, ctx) => {
    const seen = new Set<string>();
    callouts.forEach((callout, index) => {
      if (seen.has(callout.name)) {
        ctx.addIssue({
          code: 'custom',
          path: [index, 'name'],
          message: `duplicate callout name "${callout.name}"`,
        });
      }
      seen.add(callout.name);
    });
  });

/**
 * One profile as it appears inside a map summary: `imageUrl` is the ready
 * `tactics-map://…` URL (E22.2 protocol) — main builds it, the renderer
 * never sees file names or paths.
 */
export const mapProfileSummarySchema = z.object({
  id: profileIdSchema,
  name: z.string().min(1),
  imageUrl: z.string().min(1),
});

export type MapProfileSummary = z.infer<typeof mapProfileSummarySchema>;

/**
 * One `maps.list` entry (contract §5.3, MVP-07/11): the catalog row with its
 * profiles. Upload state is derived, not duplicated: a map without an image
 * is exactly a map with an empty `profiles` array. `defaultProfileId` is the
 * resolved default (explicit marker or first by creation, ADR-045) and
 * absent only when the map has no profiles.
 */
export const mapSummarySchema = z.object({
  id: mapIdSchema,
  displayName: z.string().min(1),
  profiles: z.array(mapProfileSummarySchema),
  defaultProfileId: profileIdSchema.optional(),
});

export type MapSummary = z.infer<typeof mapSummarySchema>;

/**
 * The `maps.getProfile` / mutation-response profile shape (contract §5.3,
 * MVP-08/12/13): the summary fields plus the profile's own callout set.
 * `callouts` may be empty — a user can delete every callout of a profile.
 */
export const mapProfileDetailsSchema = z.object({
  id: profileIdSchema,
  mapId: mapIdSchema,
  name: z.string().min(1),
  imageUrl: z.string().min(1),
  callouts: z.array(calloutSchema),
});

export type MapProfileDetails = z.infer<typeof mapProfileDetailsSchema>;

/**
 * Where `maps.createProfile` gets its image from (ADR-045): a fresh upload
 * (main owns the native file dialog) or a fork of an existing profile
 * (image file and callouts copied).
 */
export const createProfileSourceSchema = z.discriminatedUnion('kind', [
  z.object({ kind: z.literal('upload') }),
  z.object({ kind: z.literal('fork'), profileId: profileIdSchema }),
]);

export type CreateProfileSource = z.infer<typeof createProfileSourceSchema>;
